# Generated by Django 4.0.5 on 2022-09-24 18:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Azolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Azoning ismi: ')),
                ('text', models.CharField(max_length=50, verbose_name='Lavozimi')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram: ')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram: ')),
            ],
        ),
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha')),
                ('img', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rasm linki')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Post')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='Muallif')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.CharField(max_length=400)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.post')),
            ],
        ),
    ]
