# Generated by Django 4.0.5 on 2022-09-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azolar',
            name='img',
            field=models.CharField(default='^_^', max_length=200, verbose_name='Azoning rasmi linki'),
        ),
    ]
